[versions]
agp = "8.9.1"
kotlin = "2.0.10"
composeCompiler = "1.5.15"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
coreKtx = "1.17.0"
activityCompose = "1.9.3"
composeUi = "1.6.8"
composeMaterial3 = "1.2.1"
camera = "1.3.0"
exifinterface = "1.3.7"
firebaseAuth = "23.0.0"
firebaseAnalytics = "22.0.2"
playServicesAuth = "21.1.0"
credentials = "1.5.0"
androidGifDrawable = "1.2.17"
firebaseBom = "33.1.2"
composeBom = "2024.09.01"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "composeUi" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview"}
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling"}
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camera" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera" }
exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterface" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version.ref = "firebaseAnalytics" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentials" }
credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentials"}
android-gif-drawable = { group = "pl.droidsonroids.gif", name = "android-gif-drawable", version.ref = "androidGifDrawable" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
